#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace relaxacao_lagrangiana {
    using namespace System::Xml::Serialization;
    using namespace System;
    ref class CPLEXSolutions;
    ref class CPLEXSolution;
    ref class header;
    ref class quality;
    ref class linearConstraints;
    ref class constraint;
    ref class quadraticConstraints;
    ref class indicatorConstraints;
    ref class variables;
    ref class variable;
    
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
    public enum class headerSolutionMethodString {
        
        /// <remarks/>
        primal,
        
        /// <remarks/>
        dual,
        
        /// <remarks/>
        barrier,
        
        /// <remarks/>
        mip,
        
        /// <remarks/>
        unknown,
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
    public enum class headerSolutionTypeString {
        
        /// <remarks/>
        basic,
        
        /// <remarks/>
        nonbasic,
        
        /// <remarks/>
        primal,
        
        /// <remarks/>
        unknown,
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute]
    public enum class basisStatus {
        
        /// <remarks/>
        LL,
        
        /// <remarks/>
        UL,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        SB,
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class CPLEXSolutions {
        
        private: relaxacao_lagrangiana::CPLEXSolution^  cPLEXSolutionField;
        
        private: System::String^  versionField;
        
        /// <remarks/>
        public: property relaxacao_lagrangiana::CPLEXSolution^  CPLEXSolution {
            relaxacao_lagrangiana::CPLEXSolution^  get();
            System::Void set(relaxacao_lagrangiana::CPLEXSolution^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::String^  version {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class CPLEXSolution {
        
        private: relaxacao_lagrangiana::header^  headerField;
        
        private: relaxacao_lagrangiana::quality^  qualityField;
        
        private: relaxacao_lagrangiana::linearConstraints^  linearConstraintsField;
        
        private: relaxacao_lagrangiana::quadraticConstraints^  quadraticConstraintsField;
        
        private: relaxacao_lagrangiana::indicatorConstraints^  indicatorConstraintsField;
        
        private: relaxacao_lagrangiana::variables^  variablesField;
        
        private: System::String^  versionField;
        
        /// <remarks/>
        public: property relaxacao_lagrangiana::header^  header {
            relaxacao_lagrangiana::header^  get();
            System::Void set(relaxacao_lagrangiana::header^  value);
        }
        
        /// <remarks/>
        public: property relaxacao_lagrangiana::quality^  quality {
            relaxacao_lagrangiana::quality^  get();
            System::Void set(relaxacao_lagrangiana::quality^  value);
        }
        
        /// <remarks/>
        public: property relaxacao_lagrangiana::linearConstraints^  linearConstraints {
            relaxacao_lagrangiana::linearConstraints^  get();
            System::Void set(relaxacao_lagrangiana::linearConstraints^  value);
        }
        
        /// <remarks/>
        public: property relaxacao_lagrangiana::quadraticConstraints^  quadraticConstraints {
            relaxacao_lagrangiana::quadraticConstraints^  get();
            System::Void set(relaxacao_lagrangiana::quadraticConstraints^  value);
        }
        
        /// <remarks/>
        public: property relaxacao_lagrangiana::indicatorConstraints^  indicatorConstraints {
            relaxacao_lagrangiana::indicatorConstraints^  get();
            System::Void set(relaxacao_lagrangiana::indicatorConstraints^  value);
        }
        
        /// <remarks/>
        public: property relaxacao_lagrangiana::variables^  variables {
            relaxacao_lagrangiana::variables^  get();
            System::Void set(relaxacao_lagrangiana::variables^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::String^  version {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class header {
        
        private: relaxacao_lagrangiana::headerSolutionMethodString solutionMethodStringField;
        
        private: System::Boolean solutionMethodStringFieldSpecified;
        
        private: relaxacao_lagrangiana::headerSolutionTypeString solutionTypeStringField;
        
        private: System::Boolean solutionTypeStringFieldSpecified;
        
        private: System::String^  problemNameField;
        
        private: System::String^  solutionNameField;
        
        private: System::Int32 solutionIndexField;
        
        private: System::Boolean solutionIndexFieldSpecified;
        
        private: System::String^  solutionStatusStringField;
        
        private: System::Int32 solutionTypeValueField;
        
        private: System::Boolean solutionTypeValueFieldSpecified;
        
        private: System::Int32 solutionMethodValueField;
        
        private: System::Boolean solutionMethodValueFieldSpecified;
        
        private: System::Int32 solutionStatusValueField;
        
        private: System::Boolean solutionStatusValueFieldSpecified;
        
        private: System::Int32 simplexIterationsField;
        
        private: System::Boolean simplexIterationsFieldSpecified;
        
        private: System::Int32 barrierIterationsField;
        
        private: System::Boolean barrierIterationsFieldSpecified;
        
        private: System::Int32 mIPIterationsField;
        
        private: System::Boolean mIPIterationsFieldSpecified;
        
        private: System::Int32 mIPNodesField;
        
        private: System::Boolean mIPNodesFieldSpecified;
        
        private: System::Double objectiveValueField;
        
        private: System::Boolean objectiveValueFieldSpecified;
        
        private: System::Boolean primalFeasibleField;
        
        private: System::Boolean primalFeasibleFieldSpecified;
        
        private: System::Boolean dualFeasibleField;
        
        private: System::Boolean dualFeasibleFieldSpecified;
        
        private: System::Int32 mIPStartEffortLevelField;
        
        private: System::Boolean mIPStartEffortLevelFieldSpecified;
        
        private: System::Int32 writeLevelField;
        
        private: System::Boolean writeLevelFieldSpecified;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property relaxacao_lagrangiana::headerSolutionMethodString solutionMethodString {
            relaxacao_lagrangiana::headerSolutionMethodString get();
            System::Void set(relaxacao_lagrangiana::headerSolutionMethodString value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean solutionMethodStringSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property relaxacao_lagrangiana::headerSolutionTypeString solutionTypeString {
            relaxacao_lagrangiana::headerSolutionTypeString get();
            System::Void set(relaxacao_lagrangiana::headerSolutionTypeString value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean solutionTypeStringSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::String^  problemName {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::String^  solutionName {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 solutionIndex {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean solutionIndexSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::String^  solutionStatusString {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 solutionTypeValue {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean solutionTypeValueSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 solutionMethodValue {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean solutionMethodValueSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 solutionStatusValue {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean solutionStatusValueSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 simplexIterations {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean simplexIterationsSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 barrierIterations {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean barrierIterationsSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 MIPIterations {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean MIPIterationsSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 MIPNodes {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean MIPNodesSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double objectiveValue {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean objectiveValueSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Boolean primalFeasible {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean primalFeasibleSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Boolean dualFeasible {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean dualFeasibleSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 MIPStartEffortLevel {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean MIPStartEffortLevelSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Int32 writeLevel {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean writeLevelSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class quality {
        
        private: System::Double epOptField;
        
        private: System::Boolean epOptFieldSpecified;
        
        private: System::Double epRHSField;
        
        private: System::Boolean epRHSFieldSpecified;
        
        private: System::Double epIntField;
        
        private: System::Boolean epIntFieldSpecified;
        
        private: System::Double barEpCompField;
        
        private: System::Boolean barEpCompFieldSpecified;
        
        private: System::Double barQCPEpCompField;
        
        private: System::Boolean barQCPEpCompFieldSpecified;
        
        private: System::Double maxIntInfeasField;
        
        private: System::Boolean maxIntInfeasFieldSpecified;
        
        private: System::Double maxPrimalInfeasField;
        
        private: System::Boolean maxPrimalInfeasFieldSpecified;
        
        private: System::Double maxDualInfeasField;
        
        private: System::Boolean maxDualInfeasFieldSpecified;
        
        private: System::Double maxPrimalResidualField;
        
        private: System::Boolean maxPrimalResidualFieldSpecified;
        
        private: System::Double maxDualResidualField;
        
        private: System::Boolean maxDualResidualFieldSpecified;
        
        private: System::Double maxXField;
        
        private: System::Boolean maxXFieldSpecified;
        
        private: System::Double maxPiField;
        
        private: System::Boolean maxPiFieldSpecified;
        
        private: System::Double maxSlackField;
        
        private: System::Boolean maxSlackFieldSpecified;
        
        private: System::Double maxRedCostField;
        
        private: System::Boolean maxRedCostFieldSpecified;
        
        private: System::Double kappaField;
        
        private: System::Boolean kappaFieldSpecified;
        
        private: System::Double maxQCPrimalResidualField;
        
        private: System::Boolean maxQCPrimalResidualFieldSpecified;
        
        private: System::Double maxQCSlackInfeasField;
        
        private: System::Boolean maxQCSlackInfeasFieldSpecified;
        
        private: System::Double maxQCSlackField;
        
        private: System::Boolean maxQCSlackFieldSpecified;
        
        private: System::Double maxCompSlackField;
        
        private: System::Boolean maxCompSlackFieldSpecified;
        
        private: System::Double objGapField;
        
        private: System::Boolean objGapFieldSpecified;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double epOpt {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean epOptSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double epRHS {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean epRHSSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double epInt {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean epIntSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double barEpComp {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean barEpCompSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double barQCPEpComp {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean barQCPEpCompSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxIntInfeas {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxIntInfeasSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxPrimalInfeas {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxPrimalInfeasSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxDualInfeas {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxDualInfeasSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxPrimalResidual {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxPrimalResidualSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxDualResidual {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxDualResidualSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxX {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxXSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxPi {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxPiSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxSlack {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxSlackSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxRedCost {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxRedCostSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double kappa {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean kappaSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxQCPrimalResidual {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxQCPrimalResidualSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxQCSlackInfeas {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxQCSlackInfeasSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxQCSlack {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxQCSlackSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double maxCompSlack {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean maxCompSlackSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double objGap {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean objGapSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class linearConstraints {
        
        private: cli::array< relaxacao_lagrangiana::constraint^  >^  constraintField;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlElementAttribute(L"constraint")]
        property cli::array< relaxacao_lagrangiana::constraint^  >^  constraint {
            cli::array< relaxacao_lagrangiana::constraint^  >^  get();
            System::Void set(cli::array< relaxacao_lagrangiana::constraint^  >^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class constraint {
        
        private: System::String^  nameField;
        
        private: System::String^  indexField;
        
        private: System::Double slackField;
        
        private: System::Boolean slackFieldSpecified;
        
        private: System::Double dualField;
        
        private: System::Boolean dualFieldSpecified;
        
        private: relaxacao_lagrangiana::basisStatus statusField;
        
        private: System::Boolean statusFieldSpecified;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::String^  name {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"nonNegativeInteger")]
        property System::String^  index {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double slack {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean slackSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double dual {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean dualSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property relaxacao_lagrangiana::basisStatus status {
            relaxacao_lagrangiana::basisStatus get();
            System::Void set(relaxacao_lagrangiana::basisStatus value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean statusSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class quadraticConstraints {
        
        private: cli::array< relaxacao_lagrangiana::constraint^  >^  constraintField;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlElementAttribute(L"constraint")]
        property cli::array< relaxacao_lagrangiana::constraint^  >^  constraint {
            cli::array< relaxacao_lagrangiana::constraint^  >^  get();
            System::Void set(cli::array< relaxacao_lagrangiana::constraint^  >^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class indicatorConstraints {
        
        private: cli::array< relaxacao_lagrangiana::constraint^  >^  constraintField;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlElementAttribute(L"constraint")]
        property cli::array< relaxacao_lagrangiana::constraint^  >^  constraint {
            cli::array< relaxacao_lagrangiana::constraint^  >^  get();
            System::Void set(cli::array< relaxacao_lagrangiana::constraint^  >^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class variables {
        
        private: cli::array< relaxacao_lagrangiana::variable^  >^  variableField;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlElementAttribute(L"variable")]
        property cli::array< relaxacao_lagrangiana::variable^  >^  variable {
            cli::array< relaxacao_lagrangiana::variable^  >^  get();
            System::Void set(cli::array< relaxacao_lagrangiana::variable^  >^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.6.1055.0"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class variable {
        
        private: System::String^  nameField;
        
        private: System::String^  indexField;
        
        private: System::Double valueField;
        
        private: System::Boolean valueFieldSpecified;
        
        private: System::Double reducedCostField;
        
        private: System::Boolean reducedCostFieldSpecified;
        
        private: relaxacao_lagrangiana::basisStatus statusField;
        
        private: System::Boolean statusFieldSpecified;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::String^  name {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"nonNegativeInteger")]
        property System::String^  index {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double value {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean valueSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property System::Double reducedCost {
            System::Double get();
            System::Void set(System::Double value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean reducedCostSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlAttributeAttribute]
        property relaxacao_lagrangiana::basisStatus status {
            relaxacao_lagrangiana::basisStatus get();
            System::Void set(relaxacao_lagrangiana::basisStatus value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlIgnoreAttribute]
        property System::Boolean statusSpecified {
            System::Boolean get();
            System::Void set(System::Boolean value);
        }
    };
}
namespace relaxacao_lagrangiana {
    
    
    
    
    
    inline relaxacao_lagrangiana::CPLEXSolution^  CPLEXSolutions::CPLEXSolution::get() {
        return this->cPLEXSolutionField;
    }
    inline System::Void CPLEXSolutions::CPLEXSolution::set(relaxacao_lagrangiana::CPLEXSolution^  value) {
        this->cPLEXSolutionField = value;
    }
    
    inline System::String^  CPLEXSolutions::version::get() {
        return this->versionField;
    }
    inline System::Void CPLEXSolutions::version::set(System::String^  value) {
        this->versionField = value;
    }
    
    
    inline relaxacao_lagrangiana::header^  CPLEXSolution::header::get() {
        return this->headerField;
    }
    inline System::Void CPLEXSolution::header::set(relaxacao_lagrangiana::header^  value) {
        this->headerField = value;
    }
    
    inline relaxacao_lagrangiana::quality^  CPLEXSolution::quality::get() {
        return this->qualityField;
    }
    inline System::Void CPLEXSolution::quality::set(relaxacao_lagrangiana::quality^  value) {
        this->qualityField = value;
    }
    
    inline relaxacao_lagrangiana::linearConstraints^  CPLEXSolution::linearConstraints::get() {
        return this->linearConstraintsField;
    }
    inline System::Void CPLEXSolution::linearConstraints::set(relaxacao_lagrangiana::linearConstraints^  value) {
        this->linearConstraintsField = value;
    }
    
    inline relaxacao_lagrangiana::quadraticConstraints^  CPLEXSolution::quadraticConstraints::get() {
        return this->quadraticConstraintsField;
    }
    inline System::Void CPLEXSolution::quadraticConstraints::set(relaxacao_lagrangiana::quadraticConstraints^  value) {
        this->quadraticConstraintsField = value;
    }
    
    inline relaxacao_lagrangiana::indicatorConstraints^  CPLEXSolution::indicatorConstraints::get() {
        return this->indicatorConstraintsField;
    }
    inline System::Void CPLEXSolution::indicatorConstraints::set(relaxacao_lagrangiana::indicatorConstraints^  value) {
        this->indicatorConstraintsField = value;
    }
    
    inline relaxacao_lagrangiana::variables^  CPLEXSolution::variables::get() {
        return this->variablesField;
    }
    inline System::Void CPLEXSolution::variables::set(relaxacao_lagrangiana::variables^  value) {
        this->variablesField = value;
    }
    
    inline System::String^  CPLEXSolution::version::get() {
        return this->versionField;
    }
    inline System::Void CPLEXSolution::version::set(System::String^  value) {
        this->versionField = value;
    }
    
    
    inline relaxacao_lagrangiana::headerSolutionMethodString header::solutionMethodString::get() {
        return this->solutionMethodStringField;
    }
    inline System::Void header::solutionMethodString::set(relaxacao_lagrangiana::headerSolutionMethodString value) {
        this->solutionMethodStringField = value;
    }
    
    inline System::Boolean header::solutionMethodStringSpecified::get() {
        return this->solutionMethodStringFieldSpecified;
    }
    inline System::Void header::solutionMethodStringSpecified::set(System::Boolean value) {
        this->solutionMethodStringFieldSpecified = value;
    }
    
    inline relaxacao_lagrangiana::headerSolutionTypeString header::solutionTypeString::get() {
        return this->solutionTypeStringField;
    }
    inline System::Void header::solutionTypeString::set(relaxacao_lagrangiana::headerSolutionTypeString value) {
        this->solutionTypeStringField = value;
    }
    
    inline System::Boolean header::solutionTypeStringSpecified::get() {
        return this->solutionTypeStringFieldSpecified;
    }
    inline System::Void header::solutionTypeStringSpecified::set(System::Boolean value) {
        this->solutionTypeStringFieldSpecified = value;
    }
    
    inline System::String^  header::problemName::get() {
        return this->problemNameField;
    }
    inline System::Void header::problemName::set(System::String^  value) {
        this->problemNameField = value;
    }
    
    inline System::String^  header::solutionName::get() {
        return this->solutionNameField;
    }
    inline System::Void header::solutionName::set(System::String^  value) {
        this->solutionNameField = value;
    }
    
    inline System::Int32 header::solutionIndex::get() {
        return this->solutionIndexField;
    }
    inline System::Void header::solutionIndex::set(System::Int32 value) {
        this->solutionIndexField = value;
    }
    
    inline System::Boolean header::solutionIndexSpecified::get() {
        return this->solutionIndexFieldSpecified;
    }
    inline System::Void header::solutionIndexSpecified::set(System::Boolean value) {
        this->solutionIndexFieldSpecified = value;
    }
    
    inline System::String^  header::solutionStatusString::get() {
        return this->solutionStatusStringField;
    }
    inline System::Void header::solutionStatusString::set(System::String^  value) {
        this->solutionStatusStringField = value;
    }
    
    inline System::Int32 header::solutionTypeValue::get() {
        return this->solutionTypeValueField;
    }
    inline System::Void header::solutionTypeValue::set(System::Int32 value) {
        this->solutionTypeValueField = value;
    }
    
    inline System::Boolean header::solutionTypeValueSpecified::get() {
        return this->solutionTypeValueFieldSpecified;
    }
    inline System::Void header::solutionTypeValueSpecified::set(System::Boolean value) {
        this->solutionTypeValueFieldSpecified = value;
    }
    
    inline System::Int32 header::solutionMethodValue::get() {
        return this->solutionMethodValueField;
    }
    inline System::Void header::solutionMethodValue::set(System::Int32 value) {
        this->solutionMethodValueField = value;
    }
    
    inline System::Boolean header::solutionMethodValueSpecified::get() {
        return this->solutionMethodValueFieldSpecified;
    }
    inline System::Void header::solutionMethodValueSpecified::set(System::Boolean value) {
        this->solutionMethodValueFieldSpecified = value;
    }
    
    inline System::Int32 header::solutionStatusValue::get() {
        return this->solutionStatusValueField;
    }
    inline System::Void header::solutionStatusValue::set(System::Int32 value) {
        this->solutionStatusValueField = value;
    }
    
    inline System::Boolean header::solutionStatusValueSpecified::get() {
        return this->solutionStatusValueFieldSpecified;
    }
    inline System::Void header::solutionStatusValueSpecified::set(System::Boolean value) {
        this->solutionStatusValueFieldSpecified = value;
    }
    
    inline System::Int32 header::simplexIterations::get() {
        return this->simplexIterationsField;
    }
    inline System::Void header::simplexIterations::set(System::Int32 value) {
        this->simplexIterationsField = value;
    }
    
    inline System::Boolean header::simplexIterationsSpecified::get() {
        return this->simplexIterationsFieldSpecified;
    }
    inline System::Void header::simplexIterationsSpecified::set(System::Boolean value) {
        this->simplexIterationsFieldSpecified = value;
    }
    
    inline System::Int32 header::barrierIterations::get() {
        return this->barrierIterationsField;
    }
    inline System::Void header::barrierIterations::set(System::Int32 value) {
        this->barrierIterationsField = value;
    }
    
    inline System::Boolean header::barrierIterationsSpecified::get() {
        return this->barrierIterationsFieldSpecified;
    }
    inline System::Void header::barrierIterationsSpecified::set(System::Boolean value) {
        this->barrierIterationsFieldSpecified = value;
    }
    
    inline System::Int32 header::MIPIterations::get() {
        return this->mIPIterationsField;
    }
    inline System::Void header::MIPIterations::set(System::Int32 value) {
        this->mIPIterationsField = value;
    }
    
    inline System::Boolean header::MIPIterationsSpecified::get() {
        return this->mIPIterationsFieldSpecified;
    }
    inline System::Void header::MIPIterationsSpecified::set(System::Boolean value) {
        this->mIPIterationsFieldSpecified = value;
    }
    
    inline System::Int32 header::MIPNodes::get() {
        return this->mIPNodesField;
    }
    inline System::Void header::MIPNodes::set(System::Int32 value) {
        this->mIPNodesField = value;
    }
    
    inline System::Boolean header::MIPNodesSpecified::get() {
        return this->mIPNodesFieldSpecified;
    }
    inline System::Void header::MIPNodesSpecified::set(System::Boolean value) {
        this->mIPNodesFieldSpecified = value;
    }
    
    inline System::Double header::objectiveValue::get() {
        return this->objectiveValueField;
    }
    inline System::Void header::objectiveValue::set(System::Double value) {
        this->objectiveValueField = value;
    }
    
    inline System::Boolean header::objectiveValueSpecified::get() {
        return this->objectiveValueFieldSpecified;
    }
    inline System::Void header::objectiveValueSpecified::set(System::Boolean value) {
        this->objectiveValueFieldSpecified = value;
    }
    
    inline System::Boolean header::primalFeasible::get() {
        return this->primalFeasibleField;
    }
    inline System::Void header::primalFeasible::set(System::Boolean value) {
        this->primalFeasibleField = value;
    }
    
    inline System::Boolean header::primalFeasibleSpecified::get() {
        return this->primalFeasibleFieldSpecified;
    }
    inline System::Void header::primalFeasibleSpecified::set(System::Boolean value) {
        this->primalFeasibleFieldSpecified = value;
    }
    
    inline System::Boolean header::dualFeasible::get() {
        return this->dualFeasibleField;
    }
    inline System::Void header::dualFeasible::set(System::Boolean value) {
        this->dualFeasibleField = value;
    }
    
    inline System::Boolean header::dualFeasibleSpecified::get() {
        return this->dualFeasibleFieldSpecified;
    }
    inline System::Void header::dualFeasibleSpecified::set(System::Boolean value) {
        this->dualFeasibleFieldSpecified = value;
    }
    
    inline System::Int32 header::MIPStartEffortLevel::get() {
        return this->mIPStartEffortLevelField;
    }
    inline System::Void header::MIPStartEffortLevel::set(System::Int32 value) {
        this->mIPStartEffortLevelField = value;
    }
    
    inline System::Boolean header::MIPStartEffortLevelSpecified::get() {
        return this->mIPStartEffortLevelFieldSpecified;
    }
    inline System::Void header::MIPStartEffortLevelSpecified::set(System::Boolean value) {
        this->mIPStartEffortLevelFieldSpecified = value;
    }
    
    inline System::Int32 header::writeLevel::get() {
        return this->writeLevelField;
    }
    inline System::Void header::writeLevel::set(System::Int32 value) {
        this->writeLevelField = value;
    }
    
    inline System::Boolean header::writeLevelSpecified::get() {
        return this->writeLevelFieldSpecified;
    }
    inline System::Void header::writeLevelSpecified::set(System::Boolean value) {
        this->writeLevelFieldSpecified = value;
    }
    
    
    inline System::Double quality::epOpt::get() {
        return this->epOptField;
    }
    inline System::Void quality::epOpt::set(System::Double value) {
        this->epOptField = value;
    }
    
    inline System::Boolean quality::epOptSpecified::get() {
        return this->epOptFieldSpecified;
    }
    inline System::Void quality::epOptSpecified::set(System::Boolean value) {
        this->epOptFieldSpecified = value;
    }
    
    inline System::Double quality::epRHS::get() {
        return this->epRHSField;
    }
    inline System::Void quality::epRHS::set(System::Double value) {
        this->epRHSField = value;
    }
    
    inline System::Boolean quality::epRHSSpecified::get() {
        return this->epRHSFieldSpecified;
    }
    inline System::Void quality::epRHSSpecified::set(System::Boolean value) {
        this->epRHSFieldSpecified = value;
    }
    
    inline System::Double quality::epInt::get() {
        return this->epIntField;
    }
    inline System::Void quality::epInt::set(System::Double value) {
        this->epIntField = value;
    }
    
    inline System::Boolean quality::epIntSpecified::get() {
        return this->epIntFieldSpecified;
    }
    inline System::Void quality::epIntSpecified::set(System::Boolean value) {
        this->epIntFieldSpecified = value;
    }
    
    inline System::Double quality::barEpComp::get() {
        return this->barEpCompField;
    }
    inline System::Void quality::barEpComp::set(System::Double value) {
        this->barEpCompField = value;
    }
    
    inline System::Boolean quality::barEpCompSpecified::get() {
        return this->barEpCompFieldSpecified;
    }
    inline System::Void quality::barEpCompSpecified::set(System::Boolean value) {
        this->barEpCompFieldSpecified = value;
    }
    
    inline System::Double quality::barQCPEpComp::get() {
        return this->barQCPEpCompField;
    }
    inline System::Void quality::barQCPEpComp::set(System::Double value) {
        this->barQCPEpCompField = value;
    }
    
    inline System::Boolean quality::barQCPEpCompSpecified::get() {
        return this->barQCPEpCompFieldSpecified;
    }
    inline System::Void quality::barQCPEpCompSpecified::set(System::Boolean value) {
        this->barQCPEpCompFieldSpecified = value;
    }
    
    inline System::Double quality::maxIntInfeas::get() {
        return this->maxIntInfeasField;
    }
    inline System::Void quality::maxIntInfeas::set(System::Double value) {
        this->maxIntInfeasField = value;
    }
    
    inline System::Boolean quality::maxIntInfeasSpecified::get() {
        return this->maxIntInfeasFieldSpecified;
    }
    inline System::Void quality::maxIntInfeasSpecified::set(System::Boolean value) {
        this->maxIntInfeasFieldSpecified = value;
    }
    
    inline System::Double quality::maxPrimalInfeas::get() {
        return this->maxPrimalInfeasField;
    }
    inline System::Void quality::maxPrimalInfeas::set(System::Double value) {
        this->maxPrimalInfeasField = value;
    }
    
    inline System::Boolean quality::maxPrimalInfeasSpecified::get() {
        return this->maxPrimalInfeasFieldSpecified;
    }
    inline System::Void quality::maxPrimalInfeasSpecified::set(System::Boolean value) {
        this->maxPrimalInfeasFieldSpecified = value;
    }
    
    inline System::Double quality::maxDualInfeas::get() {
        return this->maxDualInfeasField;
    }
    inline System::Void quality::maxDualInfeas::set(System::Double value) {
        this->maxDualInfeasField = value;
    }
    
    inline System::Boolean quality::maxDualInfeasSpecified::get() {
        return this->maxDualInfeasFieldSpecified;
    }
    inline System::Void quality::maxDualInfeasSpecified::set(System::Boolean value) {
        this->maxDualInfeasFieldSpecified = value;
    }
    
    inline System::Double quality::maxPrimalResidual::get() {
        return this->maxPrimalResidualField;
    }
    inline System::Void quality::maxPrimalResidual::set(System::Double value) {
        this->maxPrimalResidualField = value;
    }
    
    inline System::Boolean quality::maxPrimalResidualSpecified::get() {
        return this->maxPrimalResidualFieldSpecified;
    }
    inline System::Void quality::maxPrimalResidualSpecified::set(System::Boolean value) {
        this->maxPrimalResidualFieldSpecified = value;
    }
    
    inline System::Double quality::maxDualResidual::get() {
        return this->maxDualResidualField;
    }
    inline System::Void quality::maxDualResidual::set(System::Double value) {
        this->maxDualResidualField = value;
    }
    
    inline System::Boolean quality::maxDualResidualSpecified::get() {
        return this->maxDualResidualFieldSpecified;
    }
    inline System::Void quality::maxDualResidualSpecified::set(System::Boolean value) {
        this->maxDualResidualFieldSpecified = value;
    }
    
    inline System::Double quality::maxX::get() {
        return this->maxXField;
    }
    inline System::Void quality::maxX::set(System::Double value) {
        this->maxXField = value;
    }
    
    inline System::Boolean quality::maxXSpecified::get() {
        return this->maxXFieldSpecified;
    }
    inline System::Void quality::maxXSpecified::set(System::Boolean value) {
        this->maxXFieldSpecified = value;
    }
    
    inline System::Double quality::maxPi::get() {
        return this->maxPiField;
    }
    inline System::Void quality::maxPi::set(System::Double value) {
        this->maxPiField = value;
    }
    
    inline System::Boolean quality::maxPiSpecified::get() {
        return this->maxPiFieldSpecified;
    }
    inline System::Void quality::maxPiSpecified::set(System::Boolean value) {
        this->maxPiFieldSpecified = value;
    }
    
    inline System::Double quality::maxSlack::get() {
        return this->maxSlackField;
    }
    inline System::Void quality::maxSlack::set(System::Double value) {
        this->maxSlackField = value;
    }
    
    inline System::Boolean quality::maxSlackSpecified::get() {
        return this->maxSlackFieldSpecified;
    }
    inline System::Void quality::maxSlackSpecified::set(System::Boolean value) {
        this->maxSlackFieldSpecified = value;
    }
    
    inline System::Double quality::maxRedCost::get() {
        return this->maxRedCostField;
    }
    inline System::Void quality::maxRedCost::set(System::Double value) {
        this->maxRedCostField = value;
    }
    
    inline System::Boolean quality::maxRedCostSpecified::get() {
        return this->maxRedCostFieldSpecified;
    }
    inline System::Void quality::maxRedCostSpecified::set(System::Boolean value) {
        this->maxRedCostFieldSpecified = value;
    }
    
    inline System::Double quality::kappa::get() {
        return this->kappaField;
    }
    inline System::Void quality::kappa::set(System::Double value) {
        this->kappaField = value;
    }
    
    inline System::Boolean quality::kappaSpecified::get() {
        return this->kappaFieldSpecified;
    }
    inline System::Void quality::kappaSpecified::set(System::Boolean value) {
        this->kappaFieldSpecified = value;
    }
    
    inline System::Double quality::maxQCPrimalResidual::get() {
        return this->maxQCPrimalResidualField;
    }
    inline System::Void quality::maxQCPrimalResidual::set(System::Double value) {
        this->maxQCPrimalResidualField = value;
    }
    
    inline System::Boolean quality::maxQCPrimalResidualSpecified::get() {
        return this->maxQCPrimalResidualFieldSpecified;
    }
    inline System::Void quality::maxQCPrimalResidualSpecified::set(System::Boolean value) {
        this->maxQCPrimalResidualFieldSpecified = value;
    }
    
    inline System::Double quality::maxQCSlackInfeas::get() {
        return this->maxQCSlackInfeasField;
    }
    inline System::Void quality::maxQCSlackInfeas::set(System::Double value) {
        this->maxQCSlackInfeasField = value;
    }
    
    inline System::Boolean quality::maxQCSlackInfeasSpecified::get() {
        return this->maxQCSlackInfeasFieldSpecified;
    }
    inline System::Void quality::maxQCSlackInfeasSpecified::set(System::Boolean value) {
        this->maxQCSlackInfeasFieldSpecified = value;
    }
    
    inline System::Double quality::maxQCSlack::get() {
        return this->maxQCSlackField;
    }
    inline System::Void quality::maxQCSlack::set(System::Double value) {
        this->maxQCSlackField = value;
    }
    
    inline System::Boolean quality::maxQCSlackSpecified::get() {
        return this->maxQCSlackFieldSpecified;
    }
    inline System::Void quality::maxQCSlackSpecified::set(System::Boolean value) {
        this->maxQCSlackFieldSpecified = value;
    }
    
    inline System::Double quality::maxCompSlack::get() {
        return this->maxCompSlackField;
    }
    inline System::Void quality::maxCompSlack::set(System::Double value) {
        this->maxCompSlackField = value;
    }
    
    inline System::Boolean quality::maxCompSlackSpecified::get() {
        return this->maxCompSlackFieldSpecified;
    }
    inline System::Void quality::maxCompSlackSpecified::set(System::Boolean value) {
        this->maxCompSlackFieldSpecified = value;
    }
    
    inline System::Double quality::objGap::get() {
        return this->objGapField;
    }
    inline System::Void quality::objGap::set(System::Double value) {
        this->objGapField = value;
    }
    
    inline System::Boolean quality::objGapSpecified::get() {
        return this->objGapFieldSpecified;
    }
    inline System::Void quality::objGapSpecified::set(System::Boolean value) {
        this->objGapFieldSpecified = value;
    }
    
    
    inline cli::array< relaxacao_lagrangiana::constraint^  >^  linearConstraints::constraint::get() {
        return this->constraintField;
    }
    inline System::Void linearConstraints::constraint::set(cli::array< relaxacao_lagrangiana::constraint^  >^  value) {
        this->constraintField = value;
    }
    
    
    inline System::String^  constraint::name::get() {
        return this->nameField;
    }
    inline System::Void constraint::name::set(System::String^  value) {
        this->nameField = value;
    }
    
    inline System::String^  constraint::index::get() {
        return this->indexField;
    }
    inline System::Void constraint::index::set(System::String^  value) {
        this->indexField = value;
    }
    
    inline System::Double constraint::slack::get() {
        return this->slackField;
    }
    inline System::Void constraint::slack::set(System::Double value) {
        this->slackField = value;
    }
    
    inline System::Boolean constraint::slackSpecified::get() {
        return this->slackFieldSpecified;
    }
    inline System::Void constraint::slackSpecified::set(System::Boolean value) {
        this->slackFieldSpecified = value;
    }
    
    inline System::Double constraint::dual::get() {
        return this->dualField;
    }
    inline System::Void constraint::dual::set(System::Double value) {
        this->dualField = value;
    }
    
    inline System::Boolean constraint::dualSpecified::get() {
        return this->dualFieldSpecified;
    }
    inline System::Void constraint::dualSpecified::set(System::Boolean value) {
        this->dualFieldSpecified = value;
    }
    
    inline relaxacao_lagrangiana::basisStatus constraint::status::get() {
        return this->statusField;
    }
    inline System::Void constraint::status::set(relaxacao_lagrangiana::basisStatus value) {
        this->statusField = value;
    }
    
    inline System::Boolean constraint::statusSpecified::get() {
        return this->statusFieldSpecified;
    }
    inline System::Void constraint::statusSpecified::set(System::Boolean value) {
        this->statusFieldSpecified = value;
    }
    
    
    inline cli::array< relaxacao_lagrangiana::constraint^  >^  quadraticConstraints::constraint::get() {
        return this->constraintField;
    }
    inline System::Void quadraticConstraints::constraint::set(cli::array< relaxacao_lagrangiana::constraint^  >^  value) {
        this->constraintField = value;
    }
    
    
    inline cli::array< relaxacao_lagrangiana::constraint^  >^  indicatorConstraints::constraint::get() {
        return this->constraintField;
    }
    inline System::Void indicatorConstraints::constraint::set(cli::array< relaxacao_lagrangiana::constraint^  >^  value) {
        this->constraintField = value;
    }
    
    
    inline cli::array< relaxacao_lagrangiana::variable^  >^  variables::variable::get() {
        return this->variableField;
    }
    inline System::Void variables::variable::set(cli::array< relaxacao_lagrangiana::variable^  >^  value) {
        this->variableField = value;
    }
    
    
    inline System::String^  variable::name::get() {
        return this->nameField;
    }
    inline System::Void variable::name::set(System::String^  value) {
        this->nameField = value;
    }
    
    inline System::String^  variable::index::get() {
        return this->indexField;
    }
    inline System::Void variable::index::set(System::String^  value) {
        this->indexField = value;
    }
    
    inline System::Double variable::value::get() {
        return this->valueField;
    }
    inline System::Void variable::value::set(System::Double value) {
        this->valueField = value;
    }
    
    inline System::Boolean variable::valueSpecified::get() {
        return this->valueFieldSpecified;
    }
    inline System::Void variable::valueSpecified::set(System::Boolean value) {
        this->valueFieldSpecified = value;
    }
    
    inline System::Double variable::reducedCost::get() {
        return this->reducedCostField;
    }
    inline System::Void variable::reducedCost::set(System::Double value) {
        this->reducedCostField = value;
    }
    
    inline System::Boolean variable::reducedCostSpecified::get() {
        return this->reducedCostFieldSpecified;
    }
    inline System::Void variable::reducedCostSpecified::set(System::Boolean value) {
        this->reducedCostFieldSpecified = value;
    }
    
    inline relaxacao_lagrangiana::basisStatus variable::status::get() {
        return this->statusField;
    }
    inline System::Void variable::status::set(relaxacao_lagrangiana::basisStatus value) {
        this->statusField = value;
    }
    
    inline System::Boolean variable::statusSpecified::get() {
        return this->statusFieldSpecified;
    }
    inline System::Void variable::statusSpecified::set(System::Boolean value) {
        this->statusFieldSpecified = value;
    }
}
